### ISSUE TITLE
Sei lá, tava rosinha e rosinha é de // Ps. sei mexer nisso aqui não

### ISSUE THREAD

**Issue by lordcici2020** [goltaraya/hangman-game#1]
https://github.com/goltaraya/hangman-game/blob/26035640dc4459f576d465eaecebc2cb008c1ca8/hangmangame.py#L64

**Comment by goltaraya** [comment]
AUSHAUSHUASUHASHUASHASU aq ta roxo, muito macho rapa

**Comment by lordcici2020** [comment]
Slc dá pra ver em tempo real skaksjasj

**Comment by goltaraya** [comment]
rs machiste

**Comment by lordcici2020** [comment]
**_SIM_**
